WITH TEAM_MATCHES AS (
    SELECT HOME_TEAM AS TEAM, WINNER FROM {{ref('silver_matches')}}
                    UNION ALL
    SELECT AWAY_TEAM AS TEAM, WINNER FROM {{ref('silver_matches')}}
)

SELECT 
   AVG(COUNT(WINNER)) OVER (PARTITION BY TEAM ORDER BY MATCH_NO ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS MOVING_AVG_WINS
FROM TEAM_MATCHES
GROUP BY TEAM, MATCH_NO


