WITH team_matches AS (
    SELECT HOME_TEAM AS TEAM, WINNER FROM {{ ref('silver_matches') }}
    UNION ALL
    SELECT AWAY_TEAM AS TEAM, WINNER FROM {{ ref('silver_matches') }}
)

SELECT 
    TEAM, 
    COUNT(*) AS TOTAL_MATCHES_PLAYED,
    COUNT_IF(TEAM = WINNER) AS WON,
    COUNT(*) - COUNT_IF(TEAM = WINNER) AS LOST,
    COUNT_IF(TEAM = WINNER) * 2 AS POINTS
FROM team_matches
GROUP BY TEAM
ORDER BY POINTS DESC
