SELECT
    Store_ID,
    WEEK_DATE,
    SUM(TOTAL_WEEKLY_SALES) AS TOTAL_WEEKLY_SALES,
    ROUND(AVG(TOTAL_WEEKLY_SALES),2) AS AVG_WEEKLY_SALES ,
    MAX(IS_HOLIDAY_WEEK) AS IS_HOLIDAY_WEEK
FROM {{ ref('wrk_sales') }}
GROUP BY Store_ID, WEEK_DATE
order by Store_ID



