SELECT 
    store AS Store_ID,
    TO_DATE(Date, 'DD/MM/YYYY') AS date,    
    temperature AS temperature,
    FUEL_PRICE AS FUEL_PRICE,
    MARKDOWN1 AS MARKDOWN1,
    MARKDOWN2 AS MARKDOWN2,
    MARKDOWN3 AS MARKDOWN3,
    MARKDOWN4 AS MARKDOWN4,
    MARKDOWN5 AS MARKDOWN5,
    CPI AS Consumer_price_index,
    UNEMPLOYMENT AS Unemployment_rate,
    ISHOLIDAY AS ISHOLIDAY
FROM 
    {{ source('miniproj', 'FEATURE_DATA_SET') }}
WHERE
    MARKDOWN1 IS NOT NULL
    AND MARKDOWN2 IS NOT NULL
    AND MARKDOWN3 IS NOT NULL
    AND MARKDOWN4 IS NOT NULL
    AND MARKDOWN5 IS NOT NULL;
